unit_symbol_map = {
    # Width, Depth, Height
    'cm': 'centimetre',
    'centimetre': 'centimetre',
    'centimetres': 'centimetre',
    'm': 'metre',
    'metre': 'metre',
    'metres': 'metre',
    'mm': 'millimetre',
    'millimetre': 'millimetre',
    'millimetres': 'millimetre',
    'ft': 'foot',
    'foot': 'foot',
    'feet': 'foot',
    "'": 'foot',  # symbol for foot
    'in': 'inch',
    'inch': 'inch',
    'inches': 'inch',
    '"': 'inch',  # symbol for inch
    'yd': 'yard',
    'yard': 'yard',
    'yards': 'yard',

    # Weight-related
    'g': 'gram',
    'gram': 'gram',
    'grams': 'gram',
    'kg': 'kilogram',
    'kilogram': 'kilogram',
    'kilograms': 'kilogram',
    'mg': 'milligram',
    'milligram': 'milligram',
    'milligrams': 'milligram',
    'mcg': 'microgram',
    'microgram': 'microgram',
    'micrograms': 'microgram',
    'oz': 'ounce',
    'ounce': 'ounce',
    'ounces': 'ounce',
    'lb': 'pound',
    'pound': 'pound',
    'pounds': 'pound',
    'ton': 'ton',
    'tons': 'ton',

    # Voltage
    'v': 'volt',
    'volt': 'volt',
    'volts': 'volt',
    'kv': 'kilovolt',
    'kilovolt': 'kilovolt',
    'kilovolts': 'kilovolt',
    'mv': 'millivolt',
    'millivolt': 'millivolt',
    'millivolts': 'millivolt',

    # Wattage
    'w': 'watt',
    'watt': 'watt',
    'watts': 'watt',
    'kw': 'kilowatt',
    'kilowatt': 'kilowatt',
    'kilowatts': 'kilowatt',

    # Volume
    'ml': 'millilitre',
    'millilitre': 'millilitre',
    'millilitres': 'millilitre',
    'l': 'litre',
    'litre': 'litre',
    'litres': 'litre',
    'cl': 'centilitre',
    'centilitre': 'centilitre',
    'centilitres': 'centilitre',
    'dl': 'decilitre',
    'decilitre': 'decilitre',
    'decilitres': 'decilitre',
    'fl oz': 'fluid ounce',
    'fluid ounce': 'fluid ounce',
    'fluid ounces': 'fluid ounce',
    'cup': 'cup',
    'cups': 'cup',
    'pt': 'pint',
    'pint': 'pint',
    'pints': 'pint',
    'qt': 'quart',
    'quart': 'quart',
    'quarts': 'quart',
    'gal': 'gallon',
    'gallon': 'gallon',
    'gallons': 'gallon',
    'imp gal': 'imperial gallon',
    'imperial gallon': 'imperial gallon',
    'imperial gallons': 'imperial gallon',
    'cu ft': 'cubic foot',
    'cubic foot': 'cubic foot',
    'cubic feet': 'cubic foot',
    'cu in': 'cubic inch',
    'cubic inch': 'cubic inch',
    'cubic inches': 'cubic inch',
    'μl': 'microlitre',
    'microlitre': 'microlitre',
    'microlitres': 'microlitre'
}

most_common_unit_map = {
    'width': 'metre',
    'depth': 'metre',
    'height':'metre',
    'item_weight': 'gram',
    'maximum_weight_recommendation': 'kilogram',
    'voltage': 'volt',
    'wattage': 'watt',
    'item_volume': 'litre'
}